### ISSUE TITLE
Wrong matrix dimension, julia 0.6 issue

### ISSUE THREAD

**Issue by Affie** [dehann/Caesar.jl#61]
https://github.com/dehann/Caesar.jl/blob/b72f7486625da95d453d2040ea98f5ffb74a72c7/src/VisualizationUtils.jl#L25

can be fixed by:
 gg = (x, a=0.0) -> evaluateDualTree(pl1, [x[1] x[2] x[3]]')[1]-a

**Comment by dehann** [comment]
thanks

**Comment by dehann** [comment]
add this function to unit tests for `codecov`
