### ISSUE TITLE
victoriapark_stepbystep not working in julia 0.6

### ISSUE THREAD

**Issue by Affie** [dehann/Caesar.jl#69]
Some julia 0.6 issues in example, also some plots does not work for probably the same reason.
https://github.com/dehann/Caesar.jl/blob/325dc445ce918d09de401b67f4691e51fa8457e5/examples/wheeled/victoriapark_stepbystep.jl#L15
change to
```julia
evaluateDualTree(p, point[:,:])[1] 
```
Also function not found:
https://github.com/dehann/Caesar.jl/blob/325dc445ce918d09de401b67f4691e51fa8457e5/examples/wheeled/victoriapark_stepbystep.jl#L152

**Comment by dehann-humatics** [comment]
ah, got it thanks
